"""The prevention document.

Every run writes one, whether or not the cause turned out to be a code bug.
That is deliberate: "this was a misconfiguration and here is how to recognise
it" is exactly the knowledge that never gets written down, and the next person
to see the same symptom starts from zero.

The document is assembled deterministically from fields the agent already had
to fill in, so it costs no extra model call and cannot drift from the report it
accompanies.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any

_CODE_BUG_LABEL = {
    "yes": "Yes — a defect in the source code",
    "no": "No — the code behaved as written",
    "unclear": "Not established",
}

_CATEGORY_LABEL = {
    "logic_error": "Logic error",
    "missing_validation": "Missing validation",
    "error_handling": "Error handling",
    "performance": "Performance",
    "configuration": "Configuration",
    "data_quality": "Data quality",
    "infrastructure": "Infrastructure",
    "third_party": "Third-party dependency",
    "user_error": "Expected behaviour / user error",
    "unknown": "Not classified",
}


def build_document(
    ticket: str,
    report: dict[str, Any],
    run_id: str,
    evidence_markdown: str = "",
) -> str:
    """Render the prevention write-up for one ticket."""
    pv = report.get("prevention") or {}
    rc = report.get("root_cause") or {}
    pl = report.get("plain_language") or {}
    loc = rc.get("code_location") or {}
    is_bug = pv.get("is_code_bug", "unclear")

    out: list[str] = [
        f"# Prevention notes — {ticket}",
        "",
        f"_Generated by incident_iq on {time.strftime('%Y-%m-%d')} "
        f"from run `{run_id}`. Verify before relying on it._",
        "",
        "## What happened",
        pl.get("summary") or report.get("one_line_summary", "_not recorded_"),
        "",
        "## Was this a code bug?",
        f"**{_CODE_BUG_LABEL.get(is_bug, is_bug)}**"
        + (
            f"  \nCategory: {_CATEGORY_LABEL.get(pv['category'], pv['category'])}"
            if pv.get("category")
            else ""
        ),
        "",
    ]

    if is_bug == "no":
        out += [
            "Nothing in the source code needs to change to resolve this "
            "particular ticket. That does not make it a non-event: a failure "
            "that the code permits by design is one the next person will hit "
            "the same way.",
            "",
        ]

    out += ["## Why it happened", rc.get("explanation") or "_not determined_", ""]
    if loc.get("file"):
        where = loc["file"] + (f":{loc['line']}" if loc.get("line") else "")
        out += [f"Relevant code: `{where}`"
                + (f" — {loc['why']}" if loc.get("why") else ""), ""]

    out += [
        "## What to change so it cannot happen again",
        pv.get("what_to_change") or "_not recorded_",
        "",
        "## How we would catch it next time",
        pv.get("how_to_detect_next_time") or "_not recorded_",
        "",
    ]

    if pv.get("related_risk"):
        out += [
            "## Where else this pattern may exist",
            pv["related_risk"],
            "",
        ]

    out += [
        "## Runbook entry",
        "Paste this into the service runbook:",
        "",
        "> " + (pv.get("runbook_entry") or "_not recorded_").replace("\n", "\n> "),
        "",
    ]

    prevention_items = [
        c for c in (report.get("checklist") or [])
        if isinstance(c, dict) and c.get("category") == "prevention"
    ]
    if prevention_items:
        out += ["## Follow-up actions", ""]
        for c in prevention_items:
            box = "[x]" if c.get("status") == "done" else "[ ]"
            owner = f" — {c['owner']}" if c.get("owner") else ""
            out.append(f"- {box} {c['item']}{owner}")
        out.append("")

    if evidence_markdown:
        out += ["## Evidence this was based on", "", evidence_markdown, ""]

    return "\n".join(out)


def write_document(
    run_dir: Path, ticket: str, run_id: str, body: str
) -> Path:
    """Persist alongside the run trace, one file per run."""
    target = run_dir / "prevention"
    target.mkdir(parents=True, exist_ok=True)
    path = target / f"{ticket}-{run_id}.md"
    path.write_text(body)
    return path
